version: "1.0"

services:
  app_proxy:
    environment:
      APP_HOST: alphavue-unifi-controller_server_1
      APP_PORT: 8443
  server:
    user: "1000:1000"
    image: ryansch/unifi-rpi:latest
    container_name: unifi-controller
    restart: unless-stopped
    environment:
      JAVA_OPTS: -Xmx1024M
    ports:
      - "3478:3478/udp"
      - "8080:8080"
      - "8443:8443"
      - "8880:8880"
      - "8843"
      - "6789:6789"
    environment:
      TZ: "Europe/Copenhagen"
    volumes:
      - config:/var/lib/unifi
      - log:/usr/lib/unifi/logs
      - log2:/var/log/unifi
      - run:/usr/lib/unifi/run
      - run2:/run/unifi
      - work:/usr/lib/unifi/work
